import { escapeHTML, escapeAttr } from '../../utils/Sanitize.js';
import { normalizeVoiceName } from './VoiceCore.js';
import { voiceIcon, voiceEmployeeCard, voiceReview } from './VoiceVisuals.js';
export function VoiceEmployeeView(ui,button) {
    const aliasesFor = e => ui.employeeAliases?.find(r => r.employeeId === e.id)?.aliases || [];
    const row = e => `<div data-voice-name="${escapeAttr(normalizeVoiceName([e.name,e.number,...aliasesFor(e)].join(' ')))}">${button('select',`${voiceEmployeeCard(e)}${ui.selected()?.id === e.id ? voiceIcon('check') : ''}`,ui.busy,e.id).replace('<button ',`<button aria-pressed="${ui.selected()?.id === e.id}" `)}</div>`;
    const ids = new Set(ui.matches.map(m => m.employee.id));
    const others = ui.adapter.getEmployees().filter(e => !ids.has(e.id)).sort((a,b) => String(a.number || '').localeCompare(String(b.number || ''),'es',{numeric:true}) || String(a.name).localeCompare(String(b.name),'es'));
    const needsReview = ui.selected() && ui.record.result.intent !== 'crear_prestamo';
    return `<label class="voice-search"><span class="voice-sr">Buscar por nombre, número o alias</span>${voiceIcon('search')}<input data-voice-search placeholder="Nombre o número"></label><div class="voice-all"><div class="voice-choices">${ui.matches.map(m => row(m.employee)).join('') || '<p>No encontramos coincidencias.</p>'}</div>${!ui.allEmployees && ui.matches.length ? button('choose','Ver todos') : ''}${(ui.allEmployees || !ui.matches.length) && others.length ? `<h3>Otros empleados</h3><div class="voice-choices">${others.map(row).join('')}</div>` : ''}<p data-voice-empty hidden>Sin resultados.</p></div>${needsReview ? voiceReview(ui) : ''}<details><summary>Nombre reconocido: ${escapeHTML(ui.record.mention.spokenName || ui.record.mention.spokenNumber || 'Sin identificar')}</summary><label>Nombre<input data-voice-mention="spokenName" value="${escapeAttr(ui.record.mention.spokenName || '')}"></label><label>Número<input data-voice-mention="spokenNumber" value="${escapeAttr(ui.record.mention.spokenNumber || '')}"></label>${ui.record.mention.spokenName ? '<label><input type="checkbox" data-voice-remember> Recordar pronunciación</label>' : ''}</details>${ui.selected() && !needsReview ? button('back-loan','Volver al préstamo',ui.busy) : ''}${needsReview ? button(ui.record.result.intent === 'abrir_prestamos' ? 'loans' : 'attendance',ui.record.result.intent === 'abrir_prestamos' ? 'Ir a préstamos' : 'Ver asistencia',!ui.record.reviewed) : ''}`;
}
