import { escapeHTML, escapeAttr } from '../../utils/Sanitize.js';
import { normalizeVoiceName } from './VoiceCore.js';
export function VoiceEmployeeView(ui, button) {
    const aliasesFor = e => ui.employeeAliases?.find(r => r.employeeId === e.id)?.aliases || [];
    const row = (e, reason = '') => `<div data-voice-name="${escapeAttr(normalizeVoiceName([e.name, e.number, ...aliasesFor(e)].join(' ')))}">${button('select', `<span class="voice-person"><strong>${escapeHTML(e.name)}</strong><span class="voice-code">#${escapeHTML(e.number || '—')}</span></span>`, ui.busy, e.id)}${reason ? `<small>${escapeHTML(reason)}</small>` : ''}</div>`;
    const ids = new Set(ui.matches.map(m => m.employee.id));
    const others = ui.adapter.getEmployees().filter(e => !ids.has(e.id)).sort((a,b) => String(a.number || '').localeCompare(String(b.number || ''), 'es', { numeric: true }) || String(a.name).localeCompare(String(b.name), 'es'));
    return `<p>Nombre reconocido: <strong>${escapeHTML(ui.record.mention.spokenName || ui.record.mention.spokenNumber || 'Sin identificar')}</strong></p><details><summary>Corregir nombre o número reconocido</summary><label>Nombre<input data-voice-mention="spokenName" value="${escapeAttr(ui.record.mention.spokenName || '')}"></label><label>Número<input data-voice-mention="spokenNumber" value="${escapeAttr(ui.record.mention.spokenNumber || '')}"></label></details><label>Buscar por nombre, número o alias<input data-voice-search></label>${ui.record.mention.spokenName ? `<label><input type="checkbox" data-voice-remember> Recordar esta pronunciación para el empleado elegido</label>` : ''}<div class="voice-all"><h3>Posibles coincidencias</h3><div class="voice-choices">${ui.matches.map(m => row(m.employee,m.reason)).join('') || '<p>No encontramos coincidencias.</p>'}</div>${!ui.allEmployees && ui.matches.length ? button('choose', 'Ninguno de estos · ver todos') : ''}${ui.allEmployees || !ui.matches.length ? `<h3>Todos los demás empleados</h3><div class="voice-choices">${others.map(e => row(e)).join('')}</div>` : ''}<p data-voice-empty hidden>Sin resultados. Prueba con el número o con otra parte del nombre.</p></div>${ui.selected() ? button('back-loan', 'Volver al préstamo', ui.busy) : ''}`;
}
