import { LOAN_FIELDS, voiceDraftReady, voiceBlocked } from './VoiceCore.js';
import { escapeHTML, escapeAttr } from '../../utils/Sanitize.js';
import { voiceLoanNote } from './VoiceLoanDraft.js';
import { getDateKey } from '../../utils/DateUtils.js';
const money = value => Number(value).toLocaleString('es-DO', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const fieldLabels = { principal: 'Monto', interestRate: 'Interés (%)', interestIncluded: 'Interés incluido', installmentMode: 'Cobro', installmentCount: 'Cantidad de cuotas', startDate: 'Fecha del préstamo', concept: 'Concepto / nota (opcional)' };
export function VoiceLoanView(ui, button) {
    const record = ui.record, result = record.result, selected = ui.selected();
    const disabled = ui.busy, blocked = voiceBlocked(result);
    const adapter = ui.adapter;
        let preview = '';
        if (selected && record?.draft && voiceDraftReady(record.draft)) {
            try { const p = adapter.previewLoan(selected, record.draft); preview = `<section class="voice-projection"><p>Nuevo préstamo: <strong>${money(p.total)}</strong>${p.installments?.length ? ` · Cuotas: ${p.installments.map(x => `${money(x.amount)}${x.dueDate ? ` (${escapeHTML(x.dueDate)})` : ''}`).join(' / ')}` : ''}</p><p>Saldo actual → proyectado: <strong>${money(p.current)} → ${money(p.projected)}</strong></p></section>`; } catch (_) { preview = '<p>Completa o corrige los datos para ver la proyección.</p>'; }
        }
        const loanDefaults = adapter.getLoanDefaults?.(selected) || {};
        const futurePeriods = (loanDefaults.periods || []).filter(period => period.payDate > getDateKey(new Date()));
        const loanInputs = `<fieldset ${disabled ? 'disabled' : ''}><legend>Préstamo · borrador</legend><p>${record.draft.installmentMode === 'lump' ? 'Un solo pago en la nómina seleccionada.' : 'Las cuotas usan el calendario del sistema actual de préstamos.'} </p>${LOAN_FIELDS.filter(field => field !== 'installmentFrequencyWeeks' && (field !== 'installmentCount' || record.draft.installmentMode === 'installments')).map(field => {
            const v = record.draft?.[field] ?? ''; const options = field === 'installmentMode' ? [['lump', 'Pago único'], ['installments', 'Cuotas']] : field === 'interestIncluded' ? [['true', 'Sí'], ['false', 'No']] : null;
            return `<label>${fieldLabels[field]} ${v === '' && field !== 'concept' ? '<small>Pendiente</small>' : ''}${options ? `<select data-voice-field="${field}"><option value="">Seleccionar</option>${options.map(([key, label]) => `<option value="${key}" ${String(v) === key ? 'selected' : ''}>${label}</option>`).join('')}</select>` : `<input data-voice-field="${field}" type="${field === 'startDate' ? 'date' : ['concept'].includes(field) ? 'text' : 'number'}" ${field === 'concept' ? '' : 'step="any"'} value="${escapeAttr(String(v))}">`}</label>`;
        }).join('')}${record.draft.installmentMode === 'lump' ? `<label>Nómina de cobro<select data-voice-field="dueDate"><option value="">Seleccionar fecha de pago</option>${futurePeriods.map(period => `<option value="${escapeAttr(period.payDate)}" ${record.draft.dueDate === period.payDate ? 'selected' : ''}>${escapeHTML(period.label || period.payDate)}</option>`).join('')}</select></label>${!futurePeriods.length ? '<p role="alert">Configura el calendario de nómina para elegir la próxima fecha de pago.</p>' : ''}` : ''}${selected && loanDefaults.previousRate !== null && loanDefaults.previousRate !== undefined ? button('previous-interest', `Usar tasa anterior: ${escapeHTML(String(loanDefaults.previousRate))} %`, disabled) : ''}<p>Nota que se guardará: ${escapeHTML(record.createdAt ? voiceLoanNote(record, record.draft.concept) : 'Pendiente')}</p></fieldset>${preview}${record.completedLoanId ? '<p>Esta grabación ya registró un préstamo.</p>' : ''}${button('loan', 'Aceptar y registrar préstamo', disabled || blocked || !selected || !!record.completedLoanId || !ui.loanReady() || ((result.needsReview || result.issues.length) && !record.reviewed))}`;
    return `<section class="voice-selected"><span>Empleado</span><strong>${escapeHTML(selected.name)}</strong><span class="voice-code">#${escapeHTML(selected.number || '—')}</span>${button('choose', 'Otro empleado', disabled)}</section>${loanInputs}<details><summary>Transcripción y coincidencias</summary><label>Texto entendido<textarea data-voice-transcript ${disabled ? 'disabled' : ''}>${escapeHTML(record.transcript)}</textarea></label><label>Variante reconocida<input data-voice-alias value="${escapeAttr(record.mention.spokenName || '')}"></label>${button('learn', 'Guardar esta coincidencia', disabled)}<p>Variantes guardadas: ${(ui.employeeAliases?.find(r => r.employeeId === selected.id)?.aliases || []).map(escapeHTML).join(', ') || 'Ninguna'}</p></details>`;
}
