/**
 * 👤 ProfileTabs — the 4 tab templates of the Employee Profile modal.
 *
 *   - ProfileTabResumen    : overview (positions, monthly estimate, basic info)
 *   - ProfileTabNomina     : full payroll computation + period picker + breakdown
 *   - ProfileTabAsistencia : CalendarView for the employee
 *   - ProfileTabDocumentos : payment history and notes
 *
 * The deductions / bonuses / advances HTML inside `ProfileTabNomina` is still
 * generated by helpers that live in app.js (window.generateDeductionsHTML etc.).
 * Those helpers also depend on app.js-local state, so we call them via
 * `window.*` for now. A future sprint can fold those into PayrollUI.
 */

import { state } from '../../core/AppState.js';
import { payrollService } from '../../services/index.js';
import { formatCurrency } from '../../utils/Formatters.js';
import { CalendarView } from '../../ui/components/CalendarView.js';
import icons from '../../ui/IconSystem.js';
import { ProfileStartDatePicker, ProfileEndDatePicker, ProfileHireDatePicker, calculateMonthlyEstimate } from './ProfilePickers.js';
import { renderEmployeeScheduledAdjustments } from '../payroll/PayrollAdjustmentScheduled.js';

// ─── Tab: Nómina ─────────────────────────────────────────────────────────────

export function ProfileTabNomina(emp) {
    const { periodStart, periodEnd, deductionType, deductionValue } = state.employeeProfile;

    const payroll = payrollService.calculateEmployeePayroll(
        emp.id, periodStart, periodEnd, state.employeeProfile.deductions
    );

    const startDate = new Date(periodStart + 'T00:00:00');
    const endDate = new Date(periodEnd + 'T00:00:00');
    const startFormatted = startDate.toLocaleDateString('es-DO', { day: 'numeric', month: 'short', year: 'numeric' });
    const endFormatted = endDate.toLocaleDateString('es-DO', { day: 'numeric', month: 'short', year: 'numeric' });

    const workedDays = payroll.breakdown.reduce((sum, b) => sum + b.days, 0);
    const totalHours = payroll.breakdown.reduce((sum, b) => sum + b.regularHours + b.holidayHours, 0);
    const totalOvertime = payroll.breakdown.reduce((sum, b) => sum + b.overtimeHours, 0);

    const pp = state.settings?.payPeriod;
    const lastPayment = pp?.payDay
        ? new Date(pp.payDay + 'T00:00:00').toLocaleDateString('es-DO', { day: 'numeric', month: 'short', year: 'numeric' })
        : 'No configurado';

    // Generators that still live in app.js (referenced via window for now)
    const deductionsHTML = (window.generateDeductionsHTML && window.generateDeductionsHTML(payroll)) || '';
    const bonusesHTML = (window.generateBonusesHTML && window.generateBonusesHTML(payroll)) || '';
    const advancesHTML = (window.generateAdvancesHTML && window.generateAdvancesHTML(payroll)) || '';
    const scheduledAdjustmentsHTML = renderEmployeeScheduledAdjustments(emp, {
        draft: state.employeeProfile.manualAdjustmentDraft || null
    });

    return `<div style="display: flex; flex-direction: column; gap: 20px;">
        <!-- Selector de Período -->
        <div style="background: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155;">
            <div style="font-size: 0.875rem; font-weight: 700; color: #06b6d4; margin-bottom: 12px;">
                📅 PERÍODO DE ANÁLISIS
            </div>

            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; margin-bottom: 12px;">
                <div style="position: relative;">
                    <label style="font-size: 0.75rem; color: #94a3b8; display: block; margin-bottom: 4px;">Desde:</label>
                    <div role="button" tabindex="0" data-app-fn="toggleProfileStartPicker" style="padding: 8px 12px; background: #0f172a; border: 1px solid #334155; border-radius: 6px; cursor: pointer; display: flex; align-items: center; justify-content: space-between;">
                        <span style="color: #f1f5f9; font-size: 0.875rem;">${startFormatted}</span>
                        <span style="color: #06b6d4;">📅</span>
                    </div>
                    ${state.employeeProfile.showStartPicker ? ProfileStartDatePicker() : ''}
                </div>

                <div style="position: relative;">
                    <label style="font-size: 0.75rem; color: #94a3b8; display: block; margin-bottom: 4px;">Hasta:</label>
                    <div role="button" tabindex="0" data-app-fn="toggleProfileEndPicker" style="padding: 8px 12px; background: #0f172a; border: 1px solid #334155; border-radius: 6px; cursor: pointer; display: flex; align-items: center; justify-content: space-between;">
                        <span style="color: #f1f5f9; font-size: 0.875rem;">${endFormatted}</span>
                        <span style="color: #06b6d4;">📅</span>
                    </div>
                    ${state.employeeProfile.showEndPicker ? ProfileEndDatePicker() : ''}
                </div>
            </div>

            <div style="display: flex; flex-wrap: wrap; gap: 8px;">
                <button type="button" data-app-fn="setProfilePeriod" data-arg="7days" style="padding: 6px 12px; background: ${state.employeeProfile.activePeriod === '7days' ? '#06b6d4' : '#0f172a'}; border: 1px solid ${state.employeeProfile.activePeriod === '7days' ? '#06b6d4' : '#334155'}; border-radius: 6px; color: ${state.employeeProfile.activePeriod === '7days' ? '#000' : '#94a3b8'}; cursor: pointer; font-size: 0.75rem; font-weight: 600;">
                    7 Días
                </button>
                <button type="button" data-app-fn="setProfilePeriod" data-arg="15days" style="padding: 6px 12px; background: ${state.employeeProfile.activePeriod === '15days' ? '#06b6d4' : '#0f172a'}; border: 1px solid ${state.employeeProfile.activePeriod === '15days' ? '#06b6d4' : '#334155'}; border-radius: 6px; color: ${state.employeeProfile.activePeriod === '15days' ? '#000' : '#94a3b8'}; cursor: pointer; font-size: 0.75rem; font-weight: 600;">
                    15 Días
                </button>
                <button type="button" data-app-fn="setProfilePeriod" data-arg="month" style="padding: 6px 12px; background: ${state.employeeProfile.activePeriod === 'month' ? '#06b6d4' : '#0f172a'}; border: 1px solid ${state.employeeProfile.activePeriod === 'month' ? '#06b6d4' : '#334155'}; border-radius: 6px; color: ${state.employeeProfile.activePeriod === 'month' ? '#000' : '#94a3b8'}; cursor: pointer; font-size: 0.75rem; font-weight: 600;">
                    Este Mes
                </button>
                <button type="button" data-app-fn="setProfilePeriod" data-arg="payPeriod" style="padding: 6px 12px; background: ${state.employeeProfile.activePeriod === 'payPeriod' ? '#8b5cf6' : '#0f172a'}; border: 1px solid ${state.employeeProfile.activePeriod === 'payPeriod' ? '#8b5cf6' : '#334155'}; border-radius: 6px; color: ${state.employeeProfile.activePeriod === 'payPeriod' ? '#fff' : '#8b5cf6'}; cursor: pointer; font-size: 0.75rem; font-weight: 700;">
                    🗓️ Período Actual
                </button>
                <button type="button" data-app-fn="setProfilePeriod" data-arg="lastPayment" style="padding: 6px 12px; background: ${state.employeeProfile.activePeriod === 'lastPayment' ? 'linear-gradient(135deg, #f59e0b, #fbbf24)' : 'transparent'}; border: 1px solid ${state.employeeProfile.activePeriod === 'lastPayment' ? 'transparent' : '#f59e0b'}; border-radius: 6px; color: ${state.employeeProfile.activePeriod === 'lastPayment' ? '#000' : '#f59e0b'}; cursor: pointer; font-size: 0.75rem; font-weight: 700;">
                    💰 Desde Último Pago
                </button>
            </div>

            <div style="font-size: 0.7rem; color: #64748b; margin-top: 8px;">
                💡 Último pago: ${lastPayment}
            </div>
        </div>

        <!-- Tarjetas Estadísticas -->
        <div class="profile-stats-row">
            <div class="profile-stat-card"><span>Días</span><strong>${workedDays || 0}</strong></div>
            <div class="profile-stat-card"><span>Horas</span><strong>${Math.round(totalHours)}h</strong></div>
            <div class="profile-stat-card"><span>Extras</span><strong>${Math.round(totalOvertime)}h</strong></div>
        </div>

        <!-- Resumen de Ganancias -->
        <div class="profile-earnings-row">
            <div class="profile-gross-card">
                <div class="profile-earnings-label">TOTAL BRUTO</div>
                <div class="profile-earnings-val" style="color: #f1f5f9;">$${Math.round(payroll.bruto).toLocaleString()}</div>
            </div>
            <div class="profile-net-card">
                <div class="profile-earnings-label">NETO A PAGAR</div>
                <div class="profile-earnings-val">$${Math.round(payroll.neto).toLocaleString()}</div>
            </div>
        </div>

        <!-- Desglose por Posición -->
        <div style="background: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155;">
            <div style="font-size: 0.875rem; font-weight: 700; color: #06b6d4; margin-bottom: 16px;">
                💼 DESGLOSE POR POSICIÓN
            </div>

            ${payroll.breakdown.map(b => {
        const isExpanded = state.employeeProfile.expandedPositions && state.employeeProfile.expandedPositions[b.positionId];
        return `<div data-position-id="${b.positionId}"
                     style="background: #0f172a; padding: 12px; border-radius: 8px; border-left: 4px solid ${b.positionColor}; margin-bottom: 12px; cursor: pointer; transition: all 0.2s;"
                     role="button" tabindex="0" data-app-fn="togglePositionBreakdown" data-arg="${b.positionId}"
                     onmouseover="this.style.background='#1a2332'"
                     onmouseout="this.style.background='#0f172a'">

                    <div style="display: flex; justify-content: space-between; align-items: center;">
                        <div style="display: flex; align-items: center; gap: 10px;">
                            <span class="position-arrow" style="font-size: 1.25rem; color: ${b.positionColor}; transition: transform 0.2s; display: inline-block; transform: rotate(${isExpanded ? '90deg' : '0deg'});">▶</span>
                            <span style="width: 12px; height: 12px; border-radius: 50%; background: ${b.positionColor};"></span>
                            <span style="font-size: 0.95rem; font-weight: 700; color: #f1f5f9;">${b.positionName}</span>
                        </div>
                        <span style="font-size: 1.125rem; font-weight: 700; color: #06b6d4;">$${Math.round(b.subtotal).toLocaleString()}</span>
                    </div>

                    <div class="position-details" style="display: ${isExpanded ? 'block' : 'none'}; margin-top: 12px; padding-top: 12px; border-top: 1px solid #334155; animation: slideDown 0.2s ease-out;">
                        <div style="font-size: 0.75rem; color: #94a3b8; margin-bottom: 12px;">
                            💰 Tarifa: <span style="color: #f1f5f9; font-weight: 600;">$${Math.round(b.hourlyRate)}/hora</span>
                            · <span style="color: #06b6d4;">$${Math.round(b.hourlyRate * state.settings.regularHoursPerDay)}/día</span>
                            · <span style="color: #64748b;">~$${Math.round(b.monthlyEquivalent).toLocaleString()}/mes</span>
                        </div>

                        <div style="display: flex; flex-direction: column; gap: 6px; font-size: 0.75rem; margin-bottom: 12px;">
                            <div style="display: flex; justify-content: space-between;">
                                <span style="color: #64748b;">• Días trabajados:</span>
                                <span style="color: #f1f5f9; font-weight: 600;">${b.days} días</span>
                            </div>
                            ${b.regularHours > 0 ? `
                            <div style="display: flex; justify-content: space-between;">
                                <span style="color: #64748b;">• Horas regulares:</span>
                                <span style="color: #10b981; font-weight: 600;">${b.regularHours.toFixed(1)}h × ${formatCurrency(b.hourlyRate)}/h = ${formatCurrency(b.regularAmount)}</span>
                            </div>` : ''}
                            ${b.overtimeHours > 0 ? `
                            <div style="display: flex; justify-content: space-between;">
                                <span style="color: #64748b;">• Horas extras (${state.settings.overtimeFactor}x):</span>
                                <span style="color: #3b82f6; font-weight: 600;">${b.overtimeHours.toFixed(1)}h × ${formatCurrency(b.overtimeRate)}/h = ${formatCurrency(b.overtimeAmount)}</span>
                            </div>` : ''}
                            ${b.holidayHours > 0 ? `
                            <div style="display: flex; justify-content: space-between;">
                                <span style="color: #64748b;">• Horas festivo (${state.settings.holidayFactor}x):</span>
                                <span style="color: #f59e0b; font-weight: 600;">${b.holidayHours.toFixed(1)}h × ${formatCurrency(b.holidayRate)}/h = ${formatCurrency(b.holidayAmount)}</span>
                            </div>` : ''}
                        </div>

                        <div style="border-top: 1px solid #334155; padding-top: 8px; margin-top: 8px;">
                            <div style="display: flex; justify-content: space-between; align-items: center;">
                                <span style="font-size: 0.875rem; color: #94a3b8;">Subtotal:</span>
                                <span style="font-size: 1.125rem; font-weight: 700; color: #06b6d4;">${formatCurrency(b.subtotal)}</span>
                            </div>
                        </div>
                    </div>
                </div>`;
    }).join('')}

            <div style="border-top: 2px solid #06b6d4; padding-top: 12px; margin-top: 12px;">
                <div style="display: flex; justify-content: space-between; align-items: center;">
                    <span style="font-size: 0.95rem; font-weight: 700; color: #f1f5f9;">TOTAL BRUTO:</span>
                    <span style="font-size: 1.5rem; font-weight: 700; color: #06b6d4;">${formatCurrency(payroll.bruto)}</span>
                </div>
            </div>
        </div>

        <!-- Planes programados guardados en el empleado -->
        ${scheduledAdjustmentsHTML}

        <!-- Deducciones / Bonos / Adelantos (HTML generado por app.js) -->
        <div id="deductions-section" style="background: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155; margin-bottom: 16px;">${deductionsHTML}</div>
        <div id="bonuses-section" style="background: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155; margin-bottom: 16px;">${bonusesHTML}</div>
        <div id="advances-section" style="background: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155;">${advancesHTML}</div>

        <!-- Total Neto -->
        <div id="neto-total" style="background: linear-gradient(135deg, #10b981, #06b6d4); padding: 20px; border-radius: 8px;">
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <div>
                    <div style="font-size: 0.875rem; color: rgba(0,0,0,0.7); font-weight: 600; margin-bottom: 4px;">💰 NETO A PAGAR</div>
                    <div style="font-size: 2rem; font-weight: 900; color: #000;">${formatCurrency(payroll.neto)}</div>
                </div>
            </div>
        </div>

        <!-- Acciones -->
        <div style="display: flex; flex-wrap: wrap; gap: 12px;">
            <button type="button" data-app-fn="pdf-soon" style="flex: 1; min-width: 200px; padding: 12px 16px; background: #1e293b; border: 1px solid #06b6d4; border-radius: 8px; color: #06b6d4; font-weight: 700; cursor: pointer; font-size: 0.875rem;">
                📄 Generar Recibo PDF
            </button>
            <button type="button" data-app-fn="wa-soon" style="flex: 1; min-width: 200px; padding: 12px 16px; background: linear-gradient(135deg, #25D366, #128C7E); border: none; border-radius: 8px; color: #fff; font-weight: 700; cursor: pointer; font-size: 0.875rem;">
                💬 Enviar por WhatsApp
            </button>
            <button type="button" data-app-fn="markAsPaid" style="flex: 1; min-width: 200px; padding: 12px 16px; background: linear-gradient(135deg, #f59e0b, #fbbf24); border: none; border-radius: 8px; color: #000; font-weight: 700; cursor: pointer; font-size: 0.875rem;">
                ✅ Marcar como Pagado
            </button>
        </div>
    </div>`;
}

// ─── Tab: Resumen ────────────────────────────────────────────────────────────

export function ProfileTabResumen(emp) {
    const positions = emp.positions.map(posId => {
        const pos = state.positions.find(p => p.id === posId);
        return pos ? pos.name : posId;
    }).join(', ');

    const hireDate = emp.hireDate
        ? new Date(emp.hireDate + 'T00:00:00').toLocaleDateString('es-DO', { year: 'numeric', month: 'long', day: 'numeric' })
        : 'No registrada';
    const ppResumen = state.settings?.payPeriod;
    const lastPayment = ppResumen?.payDay
        ? new Date(ppResumen.payDay + 'T00:00:00').toLocaleDateString('es-DO', { year: 'numeric', month: 'long', day: 'numeric' })
        : 'No configurado';

    const monthlyEst = calculateMonthlyEstimate(emp);

    return `<div style="display: flex; flex-direction: column; gap: 20px;">
        <div style="background: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155;">
            <div style="font-size: 0.875rem; font-weight: 700; color: #06b6d4; margin-bottom: 12px;">
                🎯 POSICIONES ACTUALES
            </div>
            <div style="font-size: 1rem; color: #f1f5f9; font-weight: 600;">
                ${positions}
            </div>
        </div>

        <div style="background: linear-gradient(135deg, rgba(16,185,129,0.1), rgba(6,182,212,0.1)); padding: 18px; border-radius: 8px; border: 1px solid rgba(16,185,129,0.3);">
            <div style="font-size: 0.875rem; font-weight: 700; color: #10b981; margin-bottom: 10px;">
                💰 SALARIO MENSUAL ESTIMADO
            </div>
            <div style="font-size: 1.8rem; font-weight: 900; color: #10b981; margin-bottom: 10px;">
                ${formatCurrency(monthlyEst.total)}
            </div>
            <div style="font-size: 0.72rem; color: #8fa3c3; line-height: 1.6;">
                ${monthlyEst.breakdown.map(b => {
        if (!b.hourlyRate || b.hourlyRate <= 0) {
            return `<div style="margin-bottom:3px; color:#f59e0b;">• ${b.position}: ⚠️ Tarifa por hora no configurada</div>`;
        }
        return `<div style="margin-bottom:3px;">• ${b.position}: ${formatCurrency(b.hourlyRate)}/h × ${b.daysPerWeek} días/sem → ${formatCurrency(b.monthly)}</div>`;
    }).join('')}
            </div>
            <div style="font-size: 0.68rem; color: #64748b; margin-top: 8px; padding-top: 8px; border-top: 1px solid rgba(100,116,139,0.2);">
                📊 Basado en ${state.settings.regularHoursPerDay}h/día × 4.33 semanas/mes
            </div>
        </div>

        <div style="background: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155;">
            <div style="font-size: 0.875rem; font-weight: 700; color: #06b6d4; margin-bottom: 12px;">
                📋 INFORMACIÓN BÁSICA
            </div>
            <div style="display: grid; gap: 10px; font-size: 0.875rem;">
                <div><span style="color: #94a3b8;">Número:</span> <span style="color: #f1f5f9; font-weight: 600;">#${emp.number}</span></div>
                <div style="display:flex; align-items:center; justify-content:space-between;">
                    <span style="color: #94a3b8;">Contratado:</span>
                    <span style="color: #f1f5f9; font-weight: 600; cursor:pointer; padding:4px 10px; border-radius:6px; background:rgba(6,182,212,0.1); border:1px solid rgba(6,182,212,0.2); transition:all 0.2s;"
                          role="button" tabindex="0" data-app-fn="toggle-profile-hire-date-picker"
                          onmouseover="this.style.background='rgba(6,182,212,0.15)'; this.style.borderColor='rgba(6,182,212,0.3)';"
                          onmouseout="this.style.background='rgba(6,182,212,0.1)'; this.style.borderColor='rgba(6,182,212,0.2)';">
                        ${hireDate} 📅
                    </span>
                </div>
                ${state.showProfileHireDatePicker ? ProfileHireDatePicker(emp) : ''}
                ${emp.phone ? `<div><span style="color: #94a3b8;">Teléfono:</span> <span style="color: #f1f5f9; font-weight: 600;">${emp.phone}</span></div>` : ''}
                ${emp.email ? `<div><span style="color: #94a3b8;">Email:</span> <span style="color: #f1f5f9; font-weight: 600;">${emp.email}</span></div>` : ''}
                <div><span style="color: #94a3b8;">Próximo pago:</span> <span style="color: #f1f5f9; font-weight: 600;">${lastPayment}</span></div>
            </div>
        </div>

        ${emp.notes ? `<div style="background: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155;">
            <div style="font-size: 0.875rem; font-weight: 700; color: #06b6d4; margin-bottom: 12px;">
                📝 NOTAS
            </div>
            <div style="font-size: 0.875rem; color: #f1f5f9; white-space: pre-wrap;">
                ${emp.notes}
            </div>
        </div>` : ''}
    </div>`;
}

// ─── Tab: Asistencia ─────────────────────────────────────────────────────────

export function ProfileTabAsistencia(emp) {
    if (typeof CalendarView !== 'function') {
        return `<div style="text-align: center; padding: 40px; color: #94a3b8;">
            <div style="font-size: 0.875rem;">Error: Componente de Calendario no cargado.</div>
        </div>`;
    }

    return `
        <div class="profile-tab-content">
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px;">
                <h3 style="margin: 0; color: #f1f5f9; font-size: 1.1rem; display: flex; align-items: center; gap: 10px;">
                    ${icons.get('calendar', { size: 20, color: '#06b6d4' })}
                    Historial de Asistencia
                </h3>
            </div>

            <div class="profile-calendar-wrapper" style="background: rgba(15, 23, 42, 0.4); padding: 24px; border-radius: 20px; border: 1px solid rgba(255,255,255,0.05);">
                ${CalendarView({
        employee: emp,
        month: state.employeeProfile?.assistanceMonth || new Date(),
        navAction: 'window.changeProfileAsistenciaMonth',
        showLegend: true
    })}
            </div>
        </div>
    `;
}

// ─── Tab: Documentos ─────────────────────────────────────────────────────────

export function ProfileTabDocumentos(emp) {
    const paymentHistory = emp.paymentHistory || [];

    return `<div style="display: flex; flex-direction: column; gap: 20px;">
        ${emp.notes ? `<div style="background: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155;">
            <div style="font-size: 0.875rem; font-weight: 700; color: #06b6d4; margin-bottom: 12px;">
                📝 NOTAS Y OBSERVACIONES
            </div>
            <div style="font-size: 0.875rem; color: #f1f5f9; white-space: pre-wrap;">
                ${emp.notes}
            </div>
        </div>` : ''}

        <div style="background: #1e293b; padding: 16px; border-radius: 8px; border: 1px solid #334155;">
            <div style="font-size: 0.875rem; font-weight: 700; color: #06b6d4; margin-bottom: 12px;">
                📜 HISTORIAL DE PAGOS
            </div>
            ${paymentHistory.length > 0 ? `
                <div style="display: flex; flex-direction: column; gap: 8px;">
                    ${paymentHistory.slice().reverse().slice(0, 10).map(p => {
        const date = new Date(p.date + 'T00:00:00').toLocaleDateString('es-DO', { year: 'numeric', month: 'short', day: 'numeric' });
        return `<div style="background: #0f172a; padding: 10px; border-radius: 6px; display: flex; justify-content: space-between; align-items: center;">
                            <div>
                                <div style="font-size: 0.875rem; color: #f1f5f9; font-weight: 600;">$${Math.round(p.amount).toLocaleString()}</div>
                                <div style="font-size: 0.7rem; color: #94a3b8;">${date}</div>
                            </div>
                            <div style="font-size: 0.7rem; color: #64748b;">${p.period}</div>
                        </div>`;
    }).join('')}
                </div>
            ` : `<div style="text-align: center; padding: 20px; color: #64748b; font-size: 0.875rem;">
                No hay pagos registrados
            </div>`}
        </div>
    </div>`;
}
