create table if not exists public.petty_cash_receipts (
    id bigint generated by default as identity primary key,
    firebase_uid text not null
        check (char_length(firebase_uid) between 1 and 128),
    transaction_id text not null
        check (transaction_id ~ '^[A-Za-z0-9_-]{1,80}$'),
    project_id text,
    period_id text,
    storage_bucket text not null default 'petty-cash-receipts',
    storage_path text not null,
    mime_type text not null
        check (mime_type in ('image/jpeg', 'image/png', 'image/webp')),
    file_size_bytes bigint
        check (file_size_bytes is null or file_size_bytes between 1 and 5242880),
    original_name text,
    ocr_data jsonb not null default '{}'::jsonb,
    movement_data jsonb not null default '{}'::jsonb,
    status text not null default 'confirmed'
        check (status in ('confirmed', 'uploaded')),
    confirmed_at timestamptz,
    uploaded_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (firebase_uid, transaction_id),
    unique (storage_bucket, storage_path)
);

create index if not exists petty_cash_receipts_uid_uploaded_idx
    on public.petty_cash_receipts (firebase_uid, uploaded_at desc);

alter table public.petty_cash_receipts enable row level security;

revoke all on table public.petty_cash_receipts from anon, authenticated;
revoke all on sequence public.petty_cash_receipts_id_seq from anon, authenticated;
grant all on table public.petty_cash_receipts to service_role;
grant usage, select on sequence public.petty_cash_receipts_id_seq to service_role;

comment on table public.petty_cash_receipts is
    'Private receipt backups created only after the user confirms a petty-cash movement.';

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'petty-cash-receipts',
    'petty-cash-receipts',
    false,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

