create table if not exists public.app_images (
    id bigint generated by default as identity primary key,
    firebase_uid text not null
        check (firebase_uid ~ '^[A-Za-z0-9_-]{1,128}$'),
    category text not null
        check (category in ('employee-profile', 'worksite-photo', 'company-image')),
    owner_type text not null
        check (
            (category = 'employee-profile' and owner_type = 'employee') or
            (category = 'worksite-photo' and owner_type = 'worksite') or
            (category = 'company-image' and owner_type = 'company')
        ),
    owner_id text not null
        check (owner_id ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,79}$'),
    asset_id text not null
        check (asset_id ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,79}$'),
    variant text not null
        check (
            (category in ('employee-profile', 'worksite-photo') and variant in ('thumbnail', 'original')) or
            (category = 'company-image' and variant in ('thumbnail', 'original', 'logo'))
        ),
    storage_bucket text not null default 'app-images'
        check (storage_bucket = 'app-images'),
    storage_path text not null
        check (
            storage_path = concat(
                firebase_uid, '/', category, '/', owner_type, '/', owner_id, '/',
                asset_id, '/', variant, '/versions/', right(storage_path, 36)
            ) and
            right(storage_path, 36) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
        ),
    mime_type text not null
        check (mime_type in ('image/jpeg', 'image/png', 'image/webp')),
    file_size_bytes bigint not null
        check (
            (category = 'employee-profile' and file_size_bytes between 1 and 5242880) or
            (category in ('worksite-photo', 'company-image') and file_size_bytes between 1 and 10485760)
        ),
    original_name text
        check (original_name is null or char_length(original_name) <= 255),
    uploaded_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint app_images_logical_key
        unique (firebase_uid, category, owner_type, owner_id, asset_id, variant),
    unique (storage_bucket, storage_path)
);

create index if not exists app_images_owner_lookup_idx
    on public.app_images (
        firebase_uid,
        category,
        owner_type,
        owner_id,
        updated_at desc
    );

alter table public.app_images enable row level security;

revoke all on table public.app_images from anon, authenticated;
revoke all on sequence public.app_images_id_seq from anon, authenticated;
grant all on table public.app_images to service_role;
grant usage, select on sequence public.app_images_id_seq to service_role;

comment on table public.app_images is
    'Private, tenant-scoped application images managed only by the app-images Edge Function.';

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'app-images',
    'app-images',
    false,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.swap_app_image_pointer(
    p_firebase_uid text,
    p_category text,
    p_owner_type text,
    p_owner_id text,
    p_asset_id text,
    p_variant text,
    p_storage_path text,
    p_mime_type text,
    p_file_size_bytes bigint,
    p_original_name text
)
returns table (
    previous_storage_path text,
    current_storage_path text,
    category text,
    owner_type text,
    owner_id text,
    asset_id text,
    variant text,
    mime_type text,
    file_size_bytes bigint,
    original_name text,
    uploaded_at timestamptz,
    updated_at timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_previous_storage_path text;
    v_asset public.app_images%rowtype;
begin
    perform pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended(
            pg_catalog.concat_ws(
                chr(31),
                p_firebase_uid,
                p_category,
                p_owner_type,
                p_owner_id,
                p_asset_id,
                p_variant
            ),
            0
        )
    );

    select image.storage_path
    into v_previous_storage_path
    from public.app_images as image
    where image.firebase_uid = p_firebase_uid
      and image.category = p_category
      and image.owner_type = p_owner_type
      and image.owner_id = p_owner_id
      and image.asset_id = p_asset_id
      and image.variant = p_variant
    for update;

    insert into public.app_images (
        firebase_uid,
        category,
        owner_type,
        owner_id,
        asset_id,
        variant,
        storage_bucket,
        storage_path,
        mime_type,
        file_size_bytes,
        original_name,
        uploaded_at,
        updated_at
    ) values (
        p_firebase_uid,
        p_category,
        p_owner_type,
        p_owner_id,
        p_asset_id,
        p_variant,
        'app-images',
        p_storage_path,
        p_mime_type,
        p_file_size_bytes,
        p_original_name,
        clock_timestamp(),
        clock_timestamp()
    )
    on conflict on constraint app_images_logical_key
    do update set
        storage_bucket = excluded.storage_bucket,
        storage_path = excluded.storage_path,
        mime_type = excluded.mime_type,
        file_size_bytes = excluded.file_size_bytes,
        original_name = excluded.original_name,
        uploaded_at = excluded.uploaded_at,
        updated_at = excluded.updated_at
    returning * into v_asset;

    return query
    select
        v_previous_storage_path,
        v_asset.storage_path,
        v_asset.category,
        v_asset.owner_type,
        v_asset.owner_id,
        v_asset.asset_id,
        v_asset.variant,
        v_asset.mime_type,
        v_asset.file_size_bytes,
        v_asset.original_name,
        v_asset.uploaded_at,
        v_asset.updated_at;
end;
$$;

create or replace function public.delete_app_image_pointer_cas(
    p_firebase_uid text,
    p_category text,
    p_owner_type text,
    p_owner_id text,
    p_asset_id text,
    p_variant text,
    p_expected_storage_path text
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_deleted boolean;
begin
    perform pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended(
            pg_catalog.concat_ws(
                chr(31),
                p_firebase_uid,
                p_category,
                p_owner_type,
                p_owner_id,
                p_asset_id,
                p_variant
            ),
            0
        )
    );

    delete from public.app_images as image
    where image.firebase_uid = p_firebase_uid
      and image.category = p_category
      and image.owner_type = p_owner_type
      and image.owner_id = p_owner_id
      and image.asset_id = p_asset_id
      and image.variant = p_variant
      and image.storage_path = p_expected_storage_path
    returning true into v_deleted;

    return coalesce(v_deleted, false);
end;
$$;

revoke all on function public.swap_app_image_pointer(
    text, text, text, text, text, text, text, text, bigint, text
) from public, anon, authenticated;
grant execute on function public.swap_app_image_pointer(
    text, text, text, text, text, text, text, text, bigint, text
) to service_role;

revoke all on function public.delete_app_image_pointer_cas(
    text, text, text, text, text, text, text
) from public, anon, authenticated;
grant execute on function public.delete_app_image_pointer_cas(
    text, text, text, text, text, text, text
) to service_role;
