-- M3: retención de comprobantes de Caja Chica.
-- ORDEN: aplicar ANTES de desplegar la versión de petty-cash-receipt que
-- escribe upload_token/deleted_at (sin estas columnas esa versión falla).
-- NO se ejecutó contra PostgreSQL/Supabase: revisar en un proyecto de prueba.
-- No hay una decisión de purga: borrar un movimiento marca el comprobante como
-- borrado (reversible) y cada versión física se conserva. Ningún paso de esta
-- migración elimina objetos de Storage ni filas existentes.

alter table public.petty_cash_receipts
    add column if not exists deleted_at timestamptz,
    add column if not exists upload_token text;

-- Re-ejecutable: cada restricción se elimina antes de volver a crearla.
alter table public.petty_cash_receipts
    drop constraint if exists petty_cash_receipts_status_check,
    drop constraint if exists petty_cash_receipts_deleted_consistency_check,
    drop constraint if exists petty_cash_receipts_upload_token_check;

alter table public.petty_cash_receipts
    add constraint petty_cash_receipts_status_check
        check (status in ('confirmed', 'uploaded', 'deleted')),
    add constraint petty_cash_receipts_deleted_consistency_check
        check ((status = 'deleted') = (deleted_at is not null)),
    add constraint petty_cash_receipts_upload_token_check
        check (upload_token is null or upload_token ~ '^[A-Za-z0-9_-]{1,80}$');

comment on column public.petty_cash_receipts.deleted_at is
    'Borrado lógico al eliminar el movimiento. El objeto de Storage se conserva; la acción restore lo revierte.';
comment on column public.petty_cash_receipts.upload_token is
    'Versión local del comprobante; su ruta física es uid/txId/upload_token.';

-- Versiones reemplazadas por una subida posterior del mismo movimiento.
create table if not exists public.petty_cash_receipt_versions (
    id bigint generated by default as identity primary key,
    firebase_uid text not null
        check (char_length(firebase_uid) between 1 and 128),
    transaction_id text not null
        check (transaction_id ~ '^[A-Za-z0-9_-]{1,80}$'),
    storage_bucket text not null,
    storage_path text not null,
    mime_type text,
    file_size_bytes bigint,
    uploaded_at timestamptz,
    deleted_at timestamptz,
    superseded_at timestamptz not null default now(),
    unique (storage_bucket, storage_path)
);

create index if not exists petty_cash_receipt_versions_owner_tx_idx
    on public.petty_cash_receipt_versions (firebase_uid, transaction_id, superseded_at desc);

alter table public.petty_cash_receipt_versions enable row level security;

revoke all on table public.petty_cash_receipt_versions from anon, authenticated;
revoke all on sequence public.petty_cash_receipt_versions_id_seq from anon, authenticated;
grant all on table public.petty_cash_receipt_versions to service_role;
grant usage, select on sequence public.petty_cash_receipt_versions_id_seq to service_role;

comment on table public.petty_cash_receipt_versions is
    'Comprobantes reemplazados. Evidencia financiera: solo una purga aprobada puede eliminarlos.';
