create table if not exists public.petty_cash_movements (
    id bigint generated by default as identity primary key,
    firebase_uid text not null
        check (char_length(firebase_uid) between 1 and 128),
    transaction_id text not null
        check (transaction_id ~ '^[A-Za-z0-9_-]{1,80}$'),
    project_id text not null
        check (char_length(project_id) between 1 and 80),
    period_id text not null
        check (char_length(period_id) between 1 and 80),
    record_number bigint not null
        check (record_number > 0),
    movement_type text not null
        check (movement_type in ('gasto', 'reposicion')),
    amount numeric(14, 2) not null
        check (amount >= 0),
    invoice_date date,
    provider text,
    ncf text,
    rnc_emisor text,
    source_created_at timestamptz not null,
    source_updated_at timestamptz not null,
    deleted_at timestamptz,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (firebase_uid, transaction_id)
);

comment on table public.petty_cash_movements is
    'Private one-way mirror of petty-cash movements. Firestore remains the source of truth.';
comment on column public.petty_cash_movements.record_number is
    'Permanent user-facing sequence within a project. Transitional collisions are accepted and repaired by clients.';
comment on column public.petty_cash_movements.payload is
    'Non-binary source snapshot for future read-only administration and recovery.';

create index if not exists petty_cash_movements_owner_project_number_idx
    on public.petty_cash_movements (firebase_uid, project_id, record_number);
create index if not exists petty_cash_movements_owner_invoice_date_idx
    on public.petty_cash_movements (firebase_uid, invoice_date desc)
    where deleted_at is null;
create index if not exists petty_cash_movements_owner_updated_idx
    on public.petty_cash_movements (firebase_uid, source_updated_at desc);

alter table public.petty_cash_movements enable row level security;

revoke all on table public.petty_cash_movements from anon, authenticated;
grant select, insert, update, delete on table public.petty_cash_movements to service_role;
grant usage, select on sequence public.petty_cash_movements_id_seq to service_role;
