import { isProjectsEnabled } from '../../config/FeatureFlags.js';
import { db, doc, getDoc, setDoc, runTransaction, serverTimestamp } from '../../data/firebase.js';
import { getDeviceId } from '../../config/Config.js';
export const REGISTRY_COLLECTION='projectRegistryV1',REGISTRY_DOC_ID='default',PROJECTS_V1_COLLECTION='projectsV1',ALIASES_V1_COLLECTION='projectAliasesV1',CANONICAL_CACHE_PREFIX='asistencia_canonical_',ALIAS_CACHE_PREFIX='asistencia_alias_';
function isValidProjectId(id){ if(!id||typeof id!=='string')return false; const t=id.trim(); return !!t&&!t.startsWith('legacy-unresolved:'); }
function registryRef(_,uid){ return doc(db,'users',String(uid),REGISTRY_COLLECTION,REGISTRY_DOC_ID); }
function projectRef(_,uid,pid){ return doc(db,'users',String(uid),PROJECTS_V1_COLLECTION,String(pid)); }
function aliasRef(_,uid,lid){ return doc(db,'users',String(uid),ALIASES_V1_COLLECTION,String(lid)); }
function canonicalCacheKey(uid){ return `${CANONICAL_CACHE_PREFIX}${String(uid)}`; }
function aliasCacheKey(uid,lid){ return `${ALIAS_CACHE_PREFIX}${String(uid)}_${String(lid)}`; }
function cacheCanonical(uid,cid){ try{ if(uid&&isValidProjectId(cid))localStorage.setItem(canonicalCacheKey(uid),String(cid)); }catch(_){ } }
function readCachedCanonical(uid){ try{ const v=localStorage.getItem(canonicalCacheKey(uid)); return isValidProjectId(v)?String(v):null; }catch(_){ return null; } }
function cacheAlias(uid,lid,cid){ try{ if(uid&&lid&&isValidProjectId(cid))localStorage.setItem(aliasCacheKey(uid,lid),String(cid)); }catch(_){ } }
function readCachedAlias(uid,lid){ try{ const v=localStorage.getItem(aliasCacheKey(uid,lid)); return isValidProjectId(v)?String(v):null; }catch(_){ return null; } }
export async function getCanonicalId(uid,{dbRef=null}={}){ if(!isProjectsEnabled())return null; if(!uid)return null; try{ const ref=registryRef(dbRef,uid); const snap=await getDoc(ref); if(!snap||typeof snap.exists!=='function'||!snap.exists())return readCachedCanonical(uid); const d=snap.data(); const c=d?.canonicalProjectId; const v=isValidProjectId(c)?String(c):null; if(v)cacheCanonical(uid,v); return v||readCachedCanonical(uid); }catch(_){ return readCachedCanonical(uid); } }
export async function resolveCanonicalAlias(uid,legacyId){ if(!isProjectsEnabled())return legacyId; if(!uid||!legacyId)return legacyId; if(!isValidProjectId(String(legacyId)))return legacyId; const cached=readCachedAlias(uid,String(legacyId)); try{ const ref=aliasRef(db,uid,String(legacyId)); const snap=await getDoc(ref); if(!snap||typeof snap.exists!=='function'||!snap.exists())return cached||legacyId; const d=snap.data(); const c=d?.canonicalId; const v=isValidProjectId(c)?String(c):null; if(v){ cacheAlias(uid,String(legacyId),v); return v; } return cached||legacyId; }catch(_){ return cached||legacyId; } }
export async function ensureAlias(uid,legacyId,canonicalId,{deviceId=null}={}){ if(!isProjectsEnabled())return false; if(!uid||!legacyId||!canonicalId)return false; if(String(legacyId)===String(canonicalId))return false; if(!isValidProjectId(String(legacyId))||!isValidProjectId(String(canonicalId)))return false; cacheAlias(uid,String(legacyId),String(canonicalId)); try{ const ref=aliasRef(db,uid,String(legacyId)); await setDoc(ref,{legacyId:String(legacyId),canonicalId:String(canonicalId),createdAt:serverTimestamp(),createdByDeviceId:deviceId||getDeviceId()},{merge:true}); return true; }catch(_){ return true; } }
export async function ensureCanonicalProject({uid,localProject,localProjectId=null}={}){ const fallback=localProjectId||localProject?.id||null; if(!isProjectsEnabled())return{canonicalId:fallback,status:'flag-off'}; if(!uid)return{canonicalId:fallback,status:'provisional-no-uid'}; if(!isValidProjectId(String(fallback)))return{canonicalId:fallback,status:'invalid-id'}; const localId=String(fallback); try{ const ex=await getCanonicalId(uid); if(ex){ cacheCanonical(uid,ex); return{canonicalId:ex,status:ex===localId?'already-canonical':'existing'}; } }catch(_){ return{canonicalId:localId,status:'provisional-fastpath-error'}; } try{ const regRef=registryRef(db,uid); const projRef=projectRef(db,uid,localId); const canonical=await runTransaction(db,async tx=>{ const snap=await tx.get(regRef); if(snap&&typeof snap.exists==='function'&&snap.exists()){ const d=snap.data(); if(isValidProjectId(d?.canonicalProjectId))return String(d.canonicalProjectId); } const now=serverTimestamp(); const dev=getDeviceId(); tx.set(regRef,{canonicalProjectId:localId,createdAt:now,updatedAt:now,createdBy:String(uid),createdByDeviceId:dev}); const proj=localProject||{id:localId,name:'Mi obra',status:'active',schemaVersion:1,createdAt:Date.now(),updatedAt:Date.now()}; tx.set(projRef,{id:String(proj.id||localId),name:proj.name||'Mi obra',status:proj.status||'active',schemaVersion:proj.schemaVersion||1,createdAt:proj.createdAt||Date.now(),updatedAt:proj.updatedAt||Date.now()}); return localId; }); cacheCanonical(uid,canonical); return{canonicalId:canonical,status:canonical===localId?'promoted':'race-existing'}; }catch(_){ try{ const again=await getCanonicalId(uid); if(again){ cacheCanonical(uid,again); return{canonicalId:again,status:'race-existing-retry'}; } }catch(_){ } return{canonicalId:localId,status:'provisional-transaction-error'}; } }
export default{getCanonicalId,resolveCanonicalAlias,ensureAlias,ensureCanonicalProject,REGISTRY_COLLECTION,PROJECTS_V1_COLLECTION,ALIASES_V1_COLLECTION};
