import { isProjectsEnabled } from '../../config/FeatureFlags.js';
import { indexedDBService } from '../../services/IndexedDBService.js';
import { MainSyncStore } from '../../services/MainSyncStore.js';
import { replaceEntityScope, peekEntityScope } from './EntityProjectScope.js';
import { DEFAULT_PROJECT_LS_KEY } from './EntityProjectScope.js';
import { ACTIVE_PROJECT_LS_KEY } from './ProjectContext.js';
import { ensureAlias } from './ProjectRegistry.js';
import { getDeviceId } from '../../config/Config.js';
export const ADOPTION_MARKER_KEY='migration.projectAdoption.v1',ADOPTION_CHUNK_SIZE=50;
function isValidProjectId(id){ if(!id||typeof id!=='string')return false; const t=id.trim(); return !!t&&!t.startsWith('legacy-unresolved:'); }
function readAdoptionMarker(){ try{ const r=localStorage.getItem(ADOPTION_MARKER_KEY); if(!r)return{v:1,done:{}}; const p=JSON.parse(r); if(!p||p.v!==1||typeof p.done!=='object')return{v:1,done:{}}; return{v:1,done:{...p.done}}; }catch(_){ return{v:1,done:{}}; } }
function writeAdoptionMarker(m){ try{ localStorage.setItem(ADOPTION_MARKER_KEY,JSON.stringify(m)); }catch(_){ } }
function adoptionKey(a,b){ return `${String(a)}->${String(b)}`; }
export function isAdoptionDone(a,b){ if(!a||!b)return false; return !!readAdoptionMarker().done[adoptionKey(a,b)]; }
function markAdoptionDone(a,b){ const m=readAdoptionMarker(); m.done[adoptionKey(a,b)]={at:Date.now(),deviceId:getDeviceId()}; writeAdoptionMarker(m); }
const yieldToUi=()=>new Promise(r=>setTimeout(r,0));
async function rewriteStoreProjectIds(store,legacy,canonical,{idb=indexedDBService,chunkSize=ADOPTION_CHUNK_SIZE}={}){ let rewritten=0,scanned=0; try{ const recs=await idb.getAll(store); scanned=recs.length; const pend=recs.filter(r=>r&&r.projectId===legacy); if(!pend.length)return{scanned,rewritten:0}; for(let i=0;i<pend.length;i+=chunkSize){ const chunk=pend.slice(i,i+chunkSize).map(r=>({...r,projectId:canonical})).filter(c=>isValidProjectId(c.projectId)); if(chunk.length){ await idb.batchUpdate(store,chunk); rewritten+=chunk.length; } if(i+chunkSize<pend.length)await yieldToUi(); } }catch(_){ } return{scanned,rewritten}; }
async function ensureProjectIdbEntry(legacy,canonical,{idb=indexedDBService}={}){ try{ const l=await idb.get('projects',String(legacy)),c=await idb.get('projects',String(canonical)); if(!l&&!c)return{created:false,keptBoth:false}; if(l&&!c){ await idb.update('projects',{...l,id:String(canonical),updatedAt:Date.now()}); return{created:true,keptBoth:true}; } if(l&&c){ if(String(l.id)!==String(c.id))console.warn('[ProjectAdoption] diagnostic: both legacy and canonical projects present — kept both',legacy,canonical); return{created:false,keptBoth:true}; } return{created:false,keptBoth:false}; }catch(_){ return{created:false,keptBoth:false}; } }
function rewriteLsPointer(k,legacy,canonical){ try{ if(localStorage.getItem(k)===String(legacy)){ localStorage.setItem(k,String(canonical)); return true; } }catch(_){ } return false; }
async function rewriteOutboxEntries(legacy,canonical,{idb=indexedDBService}={}){ let rewritten=0; try{ const all=await idb.getAll('mainSyncOutbox'); const pend=(all||[]).filter(e=>e&& (e.status==='pending'||e.status==='dead')); for(const e of pend){ let mut=false; let nxt={...e}; if(e.kind==='mirror'&&e.snapshot){ const snap=e.snapshot; for(const k of['employees','positions','leaders']){ if(Array.isArray(snap[k])){ const arr=snap[k].map(r=>r&&r.projectId===legacy?{...r,projectId:canonical}:r); if(arr.some((r,i)=>r!==snap[k][i])){ nxt.snapshot={...nxt.snapshot,[k]:arr}; mut=true; } } } } if(e.kind==='daily'&&e.scope){ let sc=false; const s={...e.scope}; if(s.projectId===legacy){ s.projectId=canonical; sc=true; } if(s.defaultProjectId===legacy){ s.defaultProjectId=canonical; sc=true; } if(sc){ nxt.scope=s; mut=true; } if(e.records&&typeof e.records==='object'){ const recs={}; let rc=false; for(const [kk,v]of Object.entries(e.records)){ if(v&&v.projectId===legacy){ recs[kk]={...v,projectId:canonical}; rc=true; }else recs[kk]=v; } if(rc){ nxt.records=recs; mut=true; } } } if(e.kind==='entities'){ for(const k of['employees','positions','leaders']){ if(Array.isArray(e[k])){ const arr=e[k].map(r=>r&&r.projectId===legacy?{...r,projectId:canonical}:r); if(arr.some((r,i)=>r!==e[k][i])){ nxt[k]=arr; mut=true; } } } } if(mut){ await idb.update('mainSyncOutbox',nxt); rewritten++; } } }catch(_){ } return rewritten; }
export async function adoptProject({legacyId,canonicalId,uid=null,deviceId=null,idb=indexedDBService,chunkSize=ADOPTION_CHUNK_SIZE,skipAlias=false}={}){ if(!isProjectsEnabled())return{skipped:true,reason:'flag-off'}; if(!isValidProjectId(String(legacyId))||!isValidProjectId(String(canonicalId)))return{skipped:true,reason:'invalid-id'}; if(String(legacyId)===String(canonicalId)){ if(!isAdoptionDone(legacyId,canonicalId))markAdoptionDone(legacyId,canonicalId); return{skipped:false,alreadyCanonical:true}; } if(isAdoptionDone(legacyId,canonicalId))return{skipped:false,alreadyDone:true}; try{ if(typeof MainSyncStore.bumpGeneration==='function')MainSyncStore.bumpGeneration(); else if(typeof MainSyncStore._testBumpGeneration==='function')MainSyncStore._testBumpGeneration(); }catch(_){ } if(!skipAlias&&uid)try{ await ensureAlias(String(uid),String(legacyId),String(canonicalId),{deviceId:deviceId||getDeviceId()}); }catch(_){ } const perStore={}; perStore.projects=await ensureProjectIdbEntry(legacyId,canonicalId,{idb}); for(const s of['employees','positions','leaders']){ perStore[s]=await rewriteStoreProjectIds(s,String(legacyId),String(canonicalId),{idb,chunkSize}); await yieldToUi(); } perStore.attendance=await rewriteStoreProjectIds('attendance',String(legacyId),String(canonicalId),{idb,chunkSize}); await yieldToUi(); perStore.mainSyncOutbox={rewritten:await rewriteOutboxEntries(String(legacyId),String(canonicalId),{idb})}; const dR=rewriteLsPointer(DEFAULT_PROJECT_LS_KEY,String(legacyId),String(canonicalId)),aR=rewriteLsPointer(ACTIVE_PROJECT_LS_KEY,String(legacyId),String(canonicalId)); try{ const cur=peekEntityScope(),nxt={...cur}; let ch=false; if(cur.defaultProjectId===String(legacyId)){ nxt.defaultProjectId=String(canonicalId); ch=true; } if(cur.projectId===String(legacyId)){ nxt.projectId=String(canonicalId); ch=true; } if(ch)replaceEntityScope(nxt); }catch(_){ } markAdoptionDone(legacyId,canonicalId); return{skipped:false,adopted:true,legacyId:String(legacyId),canonicalId:String(canonicalId),perStore,ls:{defaultRewritten:dR,activeRewritten:aR}}; }
export default{adoptProject,isAdoptionDone,ADOPTION_MARKER_KEY,ADOPTION_CHUNK_SIZE};
